### ISSUE TITLE
Time zone is not displayed on the report.

### ISSUE THREAD

**Issue by sureshkumar-skc** [christiansandberg/pytest-reporter#1]
I am running my job on jenkins slave. For debugging purpose I want the time zone of the slave as part of the report. 

Is there is any way to add in the hook?

I want to add some additional values for the suites.
<img width="765" alt="Screenshot 2020-07-20 at 8 05 09 PM" src="https://user-images.githubusercontent.com/12427607/87950047-6c718080-cac4-11ea-87d6-4b6bc5e1b743.png">

**Comment by christiansandberg** [comment]
You could use the [pytest-metadata](https://pypi.org/project/pytest-metadata/) plugin to add this information to the report.

**Comment by sureshkumar-skc** [comment]
Thanks @christiansandberg. It did worked. I have added the following code on conftest.py

```
from time import gmtime, strftime
import time

@pytest.mark.optionalhook
def pytest_metadata(metadata):
    metadata['TimeZoneOffset'] = strftime("%z", gmtime())
    metadata['TimeZoneName'] = time.tzname
```
