### ISSUE TITLE
Reporter does trigger double collection phase

### ISSUE THREAD

**Issue by mentalAdventurer** [christiansandberg/pytest-reporter#12]
# Bug description 

In some cases the reporter will trigger a double collection phase, causing problems with `pytest`. The problem most often occurs when using the `pytester` plugin. However, I have experienced this problem without using `pytester`, but have not been able to reproduce it in a controlled environment. 

Here is a minimal example to reproduce the issue:

```py
#test_test.py
import pytest

pytest_plugins = ["pytester"]

def test_test(pytester):
    pytester.runpytest_subprocess("--report","html_report.html")
```

run the example with `pytest -vs --report=htmlreprot.html test_test.py`:

### Output
```sh
============================= test session starts ==============================
platform linux -- Python 3.8.20, pytest-8.2.2, pluggy-1.5.0 -- /home/fabtsc00/.cache/pypoetry/virtualenvs/omicron-pytest-hw-zI-v-uIk-py3.8/bin/python
cachedir: .pytest_cache
rootdir: /home/fabtsc00/repos/pytest_hw
configfile: pyproject.toml
plugins: mock-3.10.0, reporter-html1-0.9.1, reporter-0.5.3, omicron-pytest-hw-0.10.1
collecting ... collected 1 item

test_test.py::test_test running: /home/fabtsc00/.cache/pypoetry/virtualenvs/omicron-pytest-hw-zI-v-uIk-py3.8/bin/python -mpytest --basetemp=/tmp/pytest-of-fabtsc00/pytest-181/test_test0/runpytest-0 --report html_report.html
     in: /tmp/pytest-of-fabtsc00/pytest-181/test_test0
============================= test session starts ==============================
platform linux -- Python 3.8.20, pytest-8.2.2, pluggy-1.5.0
rootdir: /tmp/pytest-of-fabtsc00/pytest-181/test_test0
plugins: mock-3.10.0, reporter-html1-0.9.1, reporter-0.5.3, omicron-pytest-hw-0.10.1
collected 0 items
collected 0 items

- generated report: /tmp/pytest-of-fabtsc00/pytest-181/test_test0/html_report.html -
============================ no tests ran in 0.04s =============================
PASSED

------- generated report: /home/fabtsc00/repos/pytest_hw/htmlreprot.html -------
============================== 1 passed in 0.31s ===============================
```
As you can see, the subprocess runs the collection phase twice. This causes problems when using the collection phase hooks, because `pytest` does not expect two collection phases. On request, I could provide a minimal example of this, but I think we can agree that this is undesirable behaviour.

I would like your feedback on this. I'm open to providing a fix if you can't find the time. 

# Affected version
`0.5.3`

**Comment by mentalAdventurer** [comment]
Well, I looked into it. Here is what I think is happening. Since 1c2ba25387f857c2d77664a6aad4dd1927e32b3c it checks if the list of collected items is empty instead of if it exists. This means that if a collection does not collect any items, as was the case with mine, it will re-run the collection. 

This commit was made with respect to pytest-xdist. I don't use this package and I can really understand why this is needed. I assume that this package creates the `session.items` object without doing a collection. 
Can you confirm this? @christiansandberg 


For me, reverting this commit does the trick :see_no_evil:

**Comment by christiansandberg** [comment]
Thanks for looking into it. I'm not using xdist myself either, but it makes things complicated and changes from time to time. I'm guessing there should be a way to identify that the collection is empty because of xdist and not something else.

**Comment by mentalAdventurer** [comment]
Hmm, I took a look inside the `session` class of `pytest`. I got confused because `session.items` is initialised inside the constructor, so `hasattr(session, "items")` is always True. Also, your implementation of `pytest_collection` is a hookwrapper. This means that the original `pytest_collection', which starts the collection phase by itself (according to the documentation), is also executed. 
So it makes perfect sense why this hook is executed twice. 

I guess I'm missing the original intention of this hook, because I can't think of a reason why this hook is there in the first place. Do you want to run the collection twice for some situation (what would that situation be)?

**Comment by christiansandberg** [comment]
IIRC pytest-xdist skips collection on the master node because it's only needed on the workers, but it's needed for the reporting so I had to perform a collection anyway. But it can probably be made in a smarter way.

**Comment by mentalAdventurer** [comment]
I had a quick look inside `pytest-xdist` and can confirm what you just said. In this case I would just aim for a straightforward solution, nothing too fancy. We just need to check that a collection has actually been performed.
So we can create another hook `pytest_collectstart(collector)` where we check if the collector is actually the session. So as far as `pytest-xdist` is concerned, we are only interfering with the controller and not the workers. Finally, we adjust the if statement and the sun will shine on us again.

Since code speaks more than words, here is a  quick listing:
```py
@pytest.hookimpl(tryfirst=True)
def pytest_collectstart(collector):
    if isinstance(collector, pytest.Session):
        collector.collected=True

@pytest.hookimpl(hookwrapper=True)
def pytest_collection(session):
    yield
    if not getattr(session, "collected", False) and hasattr(session.config, "_reporter"):
        # Collection was skipped (probably due to xdist)
        session.perform_collect()
```
